version: '3.9'

networks:
  net:
    driver: bridge

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:0.4.15
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - 8000:8000
    networks:
      - net
volumes:
  chroma-data:
    driver: local
